- apps/bomb/src/server.js
- apps/dance/src/server.js
- apps/dropper/src/classes/models/dropper.game.class.js
- apps/dropper/src/server.js
- packages/common/classes/models/redisUtil.class.js
- packages/common/constants/enums.js
- packages/common/protobuf/games/game/packet.proto
10초후 모든 로직 실행되도록 수정,
enum,redisUtil,packet -> dropper 추가
각 서비스 서버에 SERVER_HOST 추가
> fix:  breakFloorInterval

- apps/dance/src/classes/manager/dance.manager.js
- apps/dance/src/utils/create.notification.js
- packages/common/protobuf/games/dance/dance.proto
> update: 게임시작 패킷에 시작 시간 추가

- apps/board/src/classes/managers/board.manager.class.js
- apps/board/src/handlers/board.handlers.js
- packages/common/classes/models/redisTransaction.class.js
- packages/common/classes/models/redisUtil.class.js
- packages/common/protobuf/board/board.proto
- 게임 종료 패킷 내용 수정
- 보드, 타일 구매가 & 벌금 수정 
Ref: #85
> Fix 85 board game end

- apps/board/src/classes/managers/board.manager.class.js
> fix: 미니게임 추가 및 랜덤 방식 적용

- apps/bomb/src/classes/models/bomb.user.class.js
- apps/bomb/src/handlers/bomb.handler.js
> Fix : Bomb Player Sync

- apps/dance/src/classes/models/dance.game.class.js
> fix: TeamRank와 TeamResults를 정렬해서 반환하도록 수정

- apps/board/src/classes/managers/board.manager.class.js
- apps/board/src/constants/env.js
- ecosystem.config.json
- env로 미니게임 선택할 수 있게끔 수정
- ecosystem에 추가된 미니게임 추가
close #125
> Fix 125 board mini game select

- apps/dropper/src/classes/managers/dropper.game.manager.js
- apps/dropper/src/classes/models/dropper.server.class.js
- apps/dropper/src/handlers/dropper.handlers.js
> Feature 110 dropper

- apps/dance/src/classes/manager/dance.manager.js
- apps/dance/src/classes/models/dance.game.class.js
- apps/dance/src/classes/models/dance.server.js
- apps/dance/src/utils/create.notification.js
- packages/common/protobuf/games/dance/dance.proto
게임 종료 알림에 endTime 추가
dance 서버 redis 구독 로직 중 예외처리 추가
기존 getGameBySessionId 수정 (인자로 오던 값이 boardId 였음)
ref close #128
> FIX 128 dance of courtship

- apps/dropper/src/classes/managers/dropper.game.manager.js
- apps/dropper/src/classes/models/dropper.game.class.js
- apps/dropper/src/handlers/dropper.handlers.js
- apps/dropper/utils/dropper.notificaion.js
> fix:dropper error

- apps/board/src/classes/managers/board.manager.class.js
- apps/board/src/handlers/board.handlers.js
- packages/common/classes/models/redisTransaction.class.js
- packages/common/classes/models/redisUtil.class.js
- packages/common/protobuf/board/board.proto
- 타일 구매 응답,알림 : 타일 구매금액 추가
- 레디스값으로 미니게임 조정 
> set BOARD:MINIGAME_CHANNEL ICE
> Fix 127 purchase tile noti

- apps/dropper/src/classes/models/dropper.game.class.js
- apps/dropper/src/classes/models/dropper.user.class.js
- apps/ice/src/classes/models/ice.user.class.js
dropper import 수정
ice position 문제도 같이 수정
> fix:dropper,ice

- apps/bomb/src/classes/models/bomb.game.class.js
- apps/bomb/src/classes/models/bomb.server.class.js
- apps/bomb/src/classes/models/bomb.user.class.js
- apps/bomb/src/handlers/bomb.handler.js
- apps/bomb/test/bombTest.js
1. 위치 초기화 안되던 문제 수정
2. 혼자 남은 경우 ( 2명 ->1 명 되는 폭탄이 터질 때)  bombSessionId = 'NULL' 로 보내도록 수정
> Fix: bombMiniGame

- apps/dropper/src/classes/models/dropper.game.class.js
> fix: dropper death

- apps/dance/src/utils/create.response.js
> fix: correct undefined인 문제 수정

- apps/dance/src/classes/models/dance.game.class.js
- apps/dance/src/handlers/dance/dance.handler.js
> Fix 128 dance

- apps/board/src/classes/managers/board.manager.class.js
- apps/board/src/handlers/board.handlers.js
- apps/dart/src/classes/models/dart.server.class.js
- ecosystem.config.json
> fix: 로그 추가 및 ecosystem 수정

- apps/board/src/classes/managers/board.manager.class.js
- packages/common/classes/models/redisTransaction.class.js
> fix: 골드 관련 내용 수정

- apps/room/src/classes/models/room.dto.js
> fix: JSON.parse 예외 처리 추가, 로그 추가

- apps/auth/src/utils/joi.util.js
- apps/bomb/src/classes/managers/bomb.game.manager.js
- apps/bomb/src/classes/models/bomb.game.class.js
- apps/bomb/src/classes/models/bomb.user.class.js
- apps/bomb/src/config/config.js
- apps/bomb/src/handlers/bomb.handler.js
- apps/bomb/src/handlers/index.js
- apps/gate/src/classes/models/gate.server.class.js
- packages/common/classes/models/redisUtil.class.js
- packages/common/protobuf/games/bomb/bomb.proto
1. 강제 종료시 대응 로직 추가
2. 게임 종료 시 획득 GOLD 레디스에 반영
> Fix: Bomb Gold, End

- apps/dropper/src/classes/models/dropper.game.class.js
- apps/dropper/src/utils/calculate.gold.js
> Fix 110 dropper

- apps/dance/src/classes/models/dance.server.js
> update: dance 서버 onData 예외처리 추가

- apps/bomb/src/classes/models/bomb.game.class.js
- apps/bomb/src/handlers/bomb.handler.js
> Fix: Bomb server. setTimeout

- apps/dropper/src/classes/managers/dropper.game.manager.js
- apps/dropper/src/handlers/dropper.handlers.js
- apps/dropper/src/utils/dropper.notificaion.js
dropClose시 조건,로그 추가
endTime 값 수정
> fix: dropCloseSocket

- apps/dance/src/classes/models/dance.game.class.js
> fix: endTime 예외처리 not 연산자 추가

- apps/dance/src/classes/models/dance.game.class.js
sessoinId도 같이 초기화하는 문제 수정
ref #128
> fix: 팀 결과 초기화 수정

- apps/bomb/src/classes/models/bomb.game.class.js
보드게임 시작 시, bomb Game 뼈대가 시작 준비상태로 생성되는 문제 수정
> Fix: bomb Game

- apps/dropper/src/classes/models/dropper.game.class.js
- apps/dropper/src/handlers/dropper.handlers.js
- apps/ice/src/classes/models/ice.game.class.js
- apps/ice/src/handlers/ice.handlers.js
- apps/ice/src/utils/ice.notifications.js
dropper - isAllReady 방어 코드 추가
ice - closeSocket 코드 추가 및 isAllReady 방어코드 추가, 랭킹 정렬 추가
> fix: dropper,ice

- apps/bomb/src/classes/models/bomb.game.class.js
- apps/bomb/src/classes/models/bomb.user.class.js
- apps/bomb/src/handlers/bomb.handler.js
1. bomb 게임 종료 시, Redis- location 에서 'bomb' 필드 제거
2. isAllready 0명일 때, false 반환하도록 수정
> Fix: Bomb gameEnd

- apps/dropper/src/classes/models/dropper.game.class.js
- apps/ice/src/classes/models/ice.game.class.js
> fix: isAllReady

- apps/board/src/classes/managers/board.manager.class.js
> fix: redis update

- apps/dance/src/classes/models/dance.game.class.js
> update: 팀전에서 개인전으로 전환할 수 있도록 플래그 추가

- apps/board/src/classes/managers/board.manager.class.js
> fix: 이전 미니게임과 중복 안되게 수정

- apps/room/src/classes/manager/room.manager.js
- apps/room/src/classes/models/room.class.js
- apps/room/src/classes/models/room.validator.js
- packages/common/protobuf/games/game/packet.proto
추방 패킷 오타 수정
roomValidator 클래스 -> 유저의 정보를 파이프라인으로 한 번에 조회하도록 메소드 통합 -> 검증 시 레디스 반복 조회 제거
room 클래스 중복 검증 로직 삭제
추방 시 유저의 위치 정보도 삭제
> Feature 181 room kick

- apps/room/src/classes/manager/room.manager.js
- apps/room/src/classes/models/room.validator.js
> fix: getRoomData 중첩 구조 삭제, join 인자명 수정

- apps/dance/src/handlers/dance/dance.handler.js
> fix: 조건문 오류 수정

- apps/board/src/classes/managers/board.manager.class.js
- apps/board/src/handlers/board.handlers.js
- packages/common/classes/models/redisTransaction.class.js
> fix: 보드 -> 대기방 이동  시 데이터 수정

- apps/dance/src/classes/manager/dance.manager.js
> update: 골드 업데이트 시 board채널에 메시지 발행

- apps/bomb/src/classes/models/bomb.game.class.js
- apps/bomb/src/classes/models/bomb.user.class.js
1. 게임 종료 시, Redis 골드 업데이트 한 이후 Publish 로 boardGoldChannel 에 전파
> Fix: Bomb GameEnd Gold

- apps/dropper/src/classes/models/dropper.game.class.js
- apps/ice/src/classes/models/ice.game.class.js
> update: gold pub

- apps/board/src/handlers/board.handlers.js
> fix: 보드 페널티 방어 코드추가

- apps/board/src/classes/managers/board.manager.class.js
- apps/board/src/handlers/board.handlers.js
- apps/dart/src/classes/manager/dart.game.manager.class.js
- apps/dart/src/classes/models/dart.game.class.js
- apps/dart/src/handlers/dart.handlers.js
- packages/common/classes/models/redisTransaction.class.js
- packages/common/classes/models/redisUtil.class.js
- packages/common/protobuf/board/board.proto
> Fix 201 tile and dart

- apps/dropper/src/handlers/dropper.handlers.js
- apps/ice/src/handlers/ice.handlers.js
closeSocket 실행 전 LocationField 확인 추가
> fix: closeSocket

- apps/dance/src/handlers/dance/dance.handler.js
> update: closeSocket 방어코드 추가

- apps/dance/src/classes/models/dance.server.js
- apps/room/src/classes/manager/room.manager.js
- apps/room/src/handlers/room/room.kick.handler.js
- apps/room/src/utils/create.notification.js
- packages/common/protobuf/room/room.proto
추방 알림에 추방할 유저의 sessionId 포함하도록 수정
dance 서버 소켓 로그 삭제
ref #209
> Fix 209 room kick

- apps/dart/src/handlers/dart.handlers.js
> fix: dart noti

- apps/room/src/classes/manager/room.manager.js
> fix: 구조 분해 할당 수정

- apps/room/src/handlers/room/room.kick.handler.js
> update: 강퇴 전 룸 데이터 캐싱, 캐싱된 데이터로 noti 전송

- apps/bomb/src/utils/bomb.notifications.js
게임 종료 시, rank 오름차순으로 정렬 후 패킷 생성
> fix: 게임결과 Rank 오름차순

- apps/board/src/classes/managers/board.manager.class.js
- packages/common/classes/models/redisTransaction.class.js
- packages/common/classes/models/redisUtil.class.js
- 골드 싱크 
- 레디스 expire 누락 부분 추가
> Fix 214 board sync noti

- packages/common/classes/models/redisTransaction.class.js
- packages/common/classes/models/redisUtil.class.js
> update: TTL 없는 데이터들 TTL 추가

- apps/board/src/handlers/board.handlers.js
- packages/common/classes/models/redisUtil.class.js
- 보드, 1명 남으면 게임 종료 
- 유저 종료시 타일 정보 삭제
> Fix 222 board game end

- apps/lobby/src/classes/manager/lobby.manager.js
- apps/room/src/classes/manager/room.manager.js
유저 목록 조회 null 필터 추가
추방 로직 검증 논리 수정
ref  #86 #209
> Fix 86 lobby/room

- apps/dropper/src/classes/models/dropper.game.class.js
- apps/ice/src/classes/models/ice.game.class.js
ice, dropper - sessionIds if문 제거
> fix: sessionIds

- apps/lobby/src/classes/manager/lobby.manager.js
> fix: null 리턴 삭제, 필터 한 번 더 추가

- apps/ice/src/classes/models/ice.game.class.js
> fix: gameTimer

- apps/room/src/classes/models/room.class.js
> update: 대기방 참가 후 대기방 상태 변경

- apps/board/src/classes/managers/board.manager.class.js
> fix: 게임 시작 요청 시, 방 상태값 체크

- apps/board/src/handlers/board.handlers.js
- packages/common/protobuf/board/board.proto
> fix: 타일 구매 응답,알림 패킷 변경

- apps/auth/src/db/user/user.queries.js
- apps/auth/src/handlers/auth/auth.handler.js
- apps/auth/src/handlers/auth/logout.handler.js
- apps/auth/src/utils/auth.utils.js
- apps/auth/test/login.test.js
> Fix: AUTH Login ID

- apps/ice/src/classes/models/ice.game.class.js
- apps/ice/src/constants/states.js
game state 추가
gameEnd시 먼저 상태 변경
> Fix: gameEnd

- .github/workflows/deploy.develop.ec2.docker.yml
> fix: docker 배포용 workflow yml

- packages/common/config/logger/winston.config.js
> Fix : elk 서버 연결 재시도

- apps/ice/src/classes/managers/ice.game.manager.js
> fix: position

- apps/auth/docker-compose.yml
- apps/board/docker-compose.yml
- apps/bomb/docker-compose.yml
- apps/dance/docker-compose.yml
- apps/dart/docker-compose.yml
- apps/distributor/docker-compose.yml
- apps/dropper/docker-compose.yml
- apps/gate/docker-compose.yml
- apps/ice/docker-compose.yml
- apps/lobby/docker-compose.yml
- apps/room/docker-compose.yml
- docker-compose.yml
- packages/common/classes/models/redisTransaction.class.js
- packages/common/classes/models/redisUtil.class.js
- docker compose
- TZ, restart
- redisUtils value 예외처리
> Fix 204 docker tz and redis utils

- apps/dropper/src/classes/models/dropper.game.class.js
- apps/dropper/src/utils/calculate.gold.js
- apps/ice/src/classes/models/ice.game.class.js
- apps/ice/src/handlers/ice.handlers.js
- apps/ice/src/utils/calculate.gold.js
- yarn.lock
this.handleGameEnd - async 추가
calculateGoldByRank - await 추가
sync, damage - 방어 코드 수정
log 추가
> fix: ice,dropper

- apps/dance/src/classes/manager/dance.manager.js
> fix: 게임 결과 금액 변경

- apps/dance/src/classes/models/dance.game.class.js
- apps/dance/src/handlers/dance/dance.handler.js
> update: 게임 종료 시 팀 재설정 추가

- apps/auth/src/server.js
- apps/bomb/src/server.js
- apps/dart/src/server.js
- apps/dropper/src/server.js
- apps/ice/src/server.js
- packages/common/classes/models/client.class.js
- packages/common/classes/models/redisUtil.class.js
- packages/common/utils/packets/packet.parser.js
- packages/common/utils/serialize/serialize.js
> fix: console.log 주석 처리 및 삭제

- .gitignore
- apps/bomb/src/classes/managers/bomb.game.manager.js
- apps/filebeat/Dockerfile
- apps/filebeat/config/env.js
- apps/filebeat/docker-compose.yml
- apps/filebeat/filebeat.yml
- docker-compose-build.yml
- docker-compose.yml
- packages/common/config/logger/winston.config.js
1. 기존 winston-logstash module => filebeat 를 사용하여 logstash 에 알림
2. winstion-logstash 부분 제거
※ .env 추가 사항은 discord 에 올리겠습니다 
※ filebeat port ==> 2021
> Update: Filebeat 적용
